"use strict";(()=>{const i={info:null,carregando:!1},r=a=>a?new Date(a).toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}):"—";async function d(){i.carregando=!0;try{i.info=await Integrations.callFn("integrations",{action:"contas_email_info"})}catch(a){i.info={erro:a.message||String(a)}}finally{i.carregando=!1}}async function s(a){const{error:e}=await Cloud.client.from("caixas_email").update(a).eq("workspace_id",Cloud.ws);if(e)throw e;Object.assign(i.info.caixa,a)}function c(){const a=i.info;if(!a)return'<div class="empty">Carregando…</div>';if(a.erro)return`<div class="notice warnbox">${esc(a.erro)}</div>`;const e=a.caixa||{};return`<p class="caption" style="margin-top:-8px">Encaminhe (ou peça ao fornecedor para enviar) o e-mail com o boleto em PDF. O Jarvis lê a linha digitável — banco, valor e vencimento — e cria a conta <strong>aguardando aprovação</strong>. Nada é pago sem o seu clique.</p>
 ${a.configurado&&a.endereco?`<div class="card" style="display:flex;gap:10px;align-items:center;flex-wrap:wrap"><strong style="font-size:16px">${esc(a.endereco)}</strong><button class="small" data-cx-copiar="${esc(a.endereco)}">${icon("copy")} Copiar</button>${e.ativo?'<span class="badge ok">Recebendo</span>':'<span class="badge">Desligado</span>'}</div>`:`<div class="notice">A caixa de boletos está pronta no Jarvis; falta ligar o recebimento no Resend (domínio de recebimento, webhook e chave de leitura). ${a.endereco?`Endereço reservado: <strong>${esc(a.endereco)}</strong>.`:""}</div>`}
 <div class="navlabel" style="margin:14px 0 6px">Quem pode enviar</div>
 <label class="check-l"><input type="checkbox" class="check" data-cx-qualquer ${e.qualquer_remetente?"checked":""}> Aceitar de qualquer remetente (ex.: fornecedores mandando direto)</label>
 <div class="row" style="gap:6px;flex-wrap:wrap;margin:6px 0">${(e.remetentes||[]).map(t=>`<span class="badge info">${esc(t)} <button class="small quiet" data-cx-tirar="${esc(t)}" aria-label="Tirar ${esc(t)}">${icon("x")}</button></span>`).join("")||'<span class="caption">Ninguém na lista.</span>'}</div>
 <div class="row" style="gap:6px"><input id="cxNovo" type="email" placeholder="e-mail que encaminha boletos" style="flex:1"><button class="small" data-cx-add>${icon("plus")} Autorizar</button></div>
 <label class="check-l" style="margin-top:8px"><input type="checkbox" class="check" data-cx-ativo ${e.ativo?"checked":""}> Caixa ligada</label>
 <div class="navlabel" style="margin:14px 0 6px">Últimos e-mails recebidos</div>
 <div class="tablewrap" style="max-height:240px"><table><thead><tr><th>Quando</th><th>De · assunto</th><th>Resultado</th></tr></thead><tbody>${(a.log||[]).map(t=>`<tr><td class="caption">${r(t.recebido_em)}</td><td>${esc(t.de||"")}<br><span class="caption">${esc(t.assunto||"")}</span></td><td class="caption">${t.criados?`<span class="badge ok">${t.criados} conta(s) criada(s)</span> `:""}${(t.resultado||[]).map(o=>esc(o.titulo?`${money(o.valor)} · venc. ${o.vencimento?o.vencimento.split("-").reverse().join("/"):"?"} · ${o.fornecedor||""}`:o.motivo||"")).join("<br>")}</td></tr>`).join("")||'<tr><td colspan="3" class="empty">Nenhum e-mail recebido ainda.</td></tr>'}</tbody></table></div>
 <div class="modalfoot"><button data-action="close">Fechar</button></div>`}async function n(){modal("Boletos por e-mail",c()),await d(),document.querySelector(".modalback")&&modal("Boletos por e-mail",c())}document.addEventListener("click",async a=>{const e=a.target.closest("[data-ce-abrir-caixa],[data-cx-copiar],[data-cx-add],[data-cx-tirar]");if(e){if(e.dataset.ceAbrirCaixa!=null){n();return}if(e.dataset.cxCopiar){try{await navigator.clipboard.writeText(e.dataset.cxCopiar),toast("Endereço copiado.")}catch{toast(e.dataset.cxCopiar)}return}try{const t=i.info?.caixa;if(!t)return;if(e.dataset.cxAdd!=null){const o=String($("#cxNovo")?.value||"").trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(o))return toast("Informe um e-mail válido.");await s({remetentes:[...new Set([...t.remetentes||[],o])]}),audit("Boletos por e-mail: remetente autorizado",o)}else e.dataset.cxTirar&&(await s({remetentes:(t.remetentes||[]).filter(o=>o!==e.dataset.cxTirar)}),audit("Boletos por e-mail: remetente removido",e.dataset.cxTirar));modal("Boletos por e-mail",c())}catch(t){toast(t.message||String(t))}}}),document.addEventListener("change",async a=>{const e=a.target;if(!(!e.matches?.("[data-cx-qualquer],[data-cx-ativo]")||!i.info?.caixa))try{const t=e.matches("[data-cx-qualquer]")?{qualquer_remetente:e.checked}:{ativo:e.checked};await s(t),audit("Boletos por e-mail",JSON.stringify(t)),toast("Salvo.")}catch(t){toast(t.message||String(t)),e.checked=!e.checked}}),window.ContasEmail={abrir:n}})();
