"use strict";(()=>{Object.assign(paths,{lupa:"M11 18a7 7 0 1 1 0-14 7 7 0 0 1 0 14z M21 21l-5-5 M8 11h6 M11 8v6"});const i={per:30};window.Reiniciar?.registrar(i,["per"]);const d=a=>(a*100).toFixed(1).replace(".",",")+"%",s=a=>money(Math.round(a));function g(){const a=new Date(Date.now()-2592e5).toLocaleDateString("sv-SE"),t=new Date(Date.now()-i.per*864e5).toLocaleDateString("sv-SE"),c=db.orders.filter(e=>e.date>=t&&e.due&&e.due<a&&!(e.gross>0&&e.fee>=e.gross*.95)).map(e=>({o:e,falta:Math.max(0,net(e)-paid(e))})).filter(e=>e.falta>.5&&!b(e.o));return{n:c.length,valor:c.reduce((e,m)=>e+m.falta,0)}}const b=a=>!!a.transit;function h(){const a=window.Margem?.diagnostico?.(i.per);if(!a)return'<div class="card empty">O Radar de margem ainda não carregou.</div>';if(!a.pedidos)return`<div class="card empty">Sem pedidos com custo cadastrado nos últimos ${i.per} dias. Conecte os marketplaces e importe os custos dos produtos para gerar o diagnóstico.</div>`;const t=g(),c=a.fora.valor+a.menores.valor+a.prejuizo.valor+t.valor,e=o=>o*30/i.per,m=new Date,f=new Date(a.ini+"T12:00"),n=[];a.prejuizo.n&&n.push(`<b>Reprecificar ${a.prejuizo.n} anúncio(s) no prejuízo.</b> O preço mínimo de cada um está na tabela acima; comece pelos que mais perdem.`),a.fora.n&&n.push(`<b>Contestar ${a.fora.n} tarifa(s) acima do padrão</b> do canal para o mesmo produto (cerca de ${s(a.fora.valor)}).`),a.menores.n&&n.push(`<b>Conferir ${a.menores.n} repasse(s) abaixo do previsto</b> no Mercado Pago e abrir reclamação quando não houver devolução ou ajuste.`),t.n&&n.push(`<b>Cobrar ${t.n} repasse(s) atrasado(s)</b> dos marketplaces (${s(t.valor)} vencidos há mais de 3 dias).`);const l=a.canais.slice().sort((o,p)=>o.m-p.m)[0];l&&a.canais.length>1&&n.push(`<b>Rever frete e preços em ${esc(l.canal)}</b>, o canal com menor margem (${d(l.m)}); frete e outros custos levam ${d(l.foP)} da venda.`),a.abaixo&&n.push(`<b>${a.abaixo} anúncio(s) vendem abaixo da meta de margem</b>: o Radar mostra o preço mínimo por canal.`);const r=(o,p,j,u,w)=>`<div class="dg-card ${w||""}"><span>${o}</span><b>${j}</b><small>${p}${u?" · "+u:""}</small></div>`;return`<div class="dg-barra"><label class="caption" for="dgPer">Período</label><select id="dgPer">${[30,60,90].map(o=>`<option value="${o}" ${i.per===o?"selected":""}>Últimos ${o} dias</option>`).join("")}</select><button class="primary small" data-dg="imprimir">${icon("print")} Imprimir ou salvar PDF</button><span class="caption">Relatório de uma página para entregar ao cliente no fim do diagnóstico gratuito.</span></div>
 <article class="dg-folha">
  <div class="dg-cab"><div class="dg-marca"><img src="brand/jarvis.svg" alt="" width="40" height="40"><div><b>Jarvis</b><small>Diagnóstico de repasses e margem</small></div></div>
   <div class="dg-quem"><b>${esc(window.Cloud?.wsName||"Empresa")}</b><small>${f.toLocaleDateString("pt-BR")} a ${m.toLocaleDateString("pt-BR")} · ${a.pedidos.toLocaleString("pt-BR")} pedidos analisados</small></div></div>
  <section class="dg-achado"><small>Pontos de atenção encontrados no período</small><b>${s(c)}</b><span>≈ ${s(e(c))} por mês, somando tarifas acima do padrão, repasses abaixo do previsto ou atrasados e anúncios vendidos com prejuízo.</span></section>
  <section class="dg-kpis">${r("Vendas no período",`${a.pedidos.toLocaleString("pt-BR")} pedidos`,s(a.venda))}${r("Margem de contribuição","depois de tarifas, frete, custo e impostos",d(a.margem),"",a.margem<.05?"ruim":"bom")}${r("Lucro líquido estimado","depois das despesas da empresa",s(a.liquido),"",a.liquido<0?"ruim":"bom")}${r("Anúncios analisados",`${a.prejuizo.n} no prejuízo`,String(a.anuncios),`${a.abaixo} abaixo da meta`)}</section>
  <section><h3>Resultado por canal</h3><table class="dg-tab"><thead><tr><th>Canal</th><th class="num">Pedidos</th><th class="num">Vendas</th><th class="num">Tarifa real</th><th class="num">Frete e outros</th><th class="num">Margem</th></tr></thead>
   <tbody>${a.canais.map(o=>`<tr><td>${esc(o.canal)}</td><td class="num">${o.n.toLocaleString("pt-BR")}</td><td class="num">${s(o.venda)}</td><td class="num">${d(o.tarP)}</td><td class="num">${d(o.foP)}</td><td class="num ${o.m<0?"red":""}"><b>${d(o.m)}</b></td></tr>`).join("")}</tbody></table>
   <p class="dg-nota">Tarifa real = comissão e taxa fixa do marketplace, já descontado o rebate. Frete e outros = frete cobrado, descontos bancados pela loja e diferenças de repasse.</p></section>
  <section><h3>Onde está o dinheiro</h3><div class="dg-grid">
   ${r("Tarifas acima do padrão",`${a.fora.n} pedido(s)`,s(a.fora.valor),"cobrança acima do normal do canal",a.fora.n?"atencao":"")}
   ${r("Repasses abaixo do previsto",`${a.menores.n} pedido(s)`,s(a.menores.valor),"o marketplace pagou menos que o previsto",a.menores.n?"atencao":"")}
   ${r("Repasses atrasados",`${t.n} pedido(s)`,s(t.valor),"vencidos há mais de 3 dias",t.n?"atencao":"")}
   ${r("Vendas com prejuízo",`${a.prejuizo.n} anúncio(s)`,s(a.prejuizo.valor),"perdidos no período",a.prejuizo.n?"ruim":"")}</div></section>
  ${a.prejuizo.top.length?`<section><h3>Anúncios que mais perdem dinheiro</h3><table class="dg-tab"><thead><tr><th>Anúncio</th><th>Canal</th><th class="num">Unid.</th><th class="num">Preço atual</th><th class="num">Preço mínimo</th><th class="num">Perda</th></tr></thead>
   <tbody>${a.prejuizo.top.map(o=>`<tr><td>${esc(String(o.nome).slice(0,46))}</td><td>${esc(o.canal)}</td><td class="num">${Math.round(o.u)}</td><td class="num">${money(o.preco)}</td><td class="num"><b>${o.min?money(o.min):"—"}</b></td><td class="num red">${s(o.perda)}</td></tr>`).join("")}</tbody></table>
   <p class="dg-nota">Preço mínimo para 10% de margem de contribuição, com a tarifa e o frete reais de cada canal.</p></section>`:""}
  <section><h3>O que fazer primeiro</h3><ol class="dg-rec">${n.slice(0,5).map(o=>`<li>${o}</li>`).join("")||"<li>Nenhum ponto crítico no período. ✓</li>"}</ol></section>
  <footer class="dg-rod">Diagnóstico feito pelo Jarvis com leitura dos pedidos e repasses das plataformas conectadas${a.semCusto?`; ${a.semCusto} pedido(s) sem custo cadastrado ficaram fora`:""}. Impostos pela alíquota efetiva de ${d(a.aliq)}. Valores estimados, para conferência com a contabilidade. · jaarvis.com.br</footer>
 </article>`}function v(){document.body.classList.add("pg-diag");const a=$("#dgPer");a&&(a.onchange=()=>{i.per=Number(a.value)||30,render()})}document.addEventListener("click",a=>{a.target.closest('[data-dg="imprimir"]')&&window.print()}),setInterval(()=>document.body.classList.toggle("pg-diag",page==="diagnostico"),400),addPage("diagnostico","lupa","Diagnóstico de margem",h,"Relatório de uma página do diagnóstico gratuito: margem por canal e onde há dinheiro parado, cobrado a mais ou perdido.","",v)})();
