(()=>{const q=e=>(e?.innerText||"").replace(/ /g," ").trim();function f(){const e=document.querySelector(".pagehead h1");if(!e)return document.title;const t=e.cloneNode(!0);return t.querySelectorAll("button").forEach(o=>o.remove()),t.textContent.trim()||"Tela"}const N=()=>window.Cloud?.wsName||"",A=["janeiro","fevereiro","março","abril","maio","junho","julho","agosto","setembro","outubro","novembro","dezembro"],h=()=>{try{const e=/^(\d{4})-(\d{2})$/.exec(typeof month=="string"?month:"");return e?A[+e[2]-1]+" de "+e[1]:""}catch{return""}},B=e=>["Jarvis",f(),h()].filter(Boolean).join(" - ").replace(/[\\/:*?"<>|]+/g,"-")+"."+e,w=e=>Number(e.replace(/\./g,"").replace(",","."));function b(e){let t=e.replace(/\s+/g," ").trim().replace(/[−–—]/g,"-");if(!t||t==="-")return null;const o=t.match(/^\((.+)\)$/);if(o){const n=b(o[1]);if(n&&n.t==="n")return{...n,v:-Math.abs(n.v)}}let r=t.match(/^(-)?\s?R\$\s?(-)?\s?([\d.]+(?:,\d+)?)$/);if(r)return{t:"n",v:w(r[3])*(r[1]||r[2]?-1:1),z:'"R$" #,##0.00;-"R$" #,##0.00'};if(r=t.match(/^([+-]?[\d.]*\d(?:,(\d+))?)\s?%$/),r){const n=(r[2]||"").length;return{t:"n",v:w(r[1].replace("+",""))/100,z:n?"0."+"0".repeat(n)+"%":"0%"}}if(r=t.match(/^(\d{2})\/(\d{2})\/(\d{4})$/),r){const n=new Date(Date.UTC(+r[3],+r[2]-1,+r[1]));if(!isNaN(n))return{t:"d",v:n,z:"dd/mm/yyyy"}}return/^-?(?:\d{1,3}(?:\.\d{3})+|\d+)(?:,\d+)?$/.test(t)&&!/^-?0\d/.test(t)&&!/^\d{6,}$/.test(t)&&t.replace(/\D/g,"").length<=15?{t:"n",v:w(t),z:t.includes(",")?"#,##0.00":"#,##0"}:{t:"s",v:t}}const D=e=>{if(e.tagName!=="TH"||!e.querySelector("button,input"))return e.innerText;const t=e.cloneNode(!0);return t.querySelectorAll("button,input").forEach(o=>o.remove()),t.textContent};function E(e){const t=e.dataset?.expNum;if(typeof t=="string"&&t!==""&&isFinite(Number(t)))return{t:"n",v:Number(t),z:"0"};const o=D(e).replace(/ /g," ").trim();if(!o)return null;const r=b(o);if(r&&r.t!=="s")return r;const n=o.split(`
`).map(l=>l.trim()).filter(Boolean);if(n.length>1){const l=b(n[0]);if(l&&l.t!=="s")return l}return{t:"s",v:n.join(" · ")}}function y(e){return!!(e.offsetParent||e.getClientRects().length)}function L(e,t,o){const r=document.getElementById("view")||document.body,n=".tablebox,.card,.relout,section,.caixa,.formcard,.dg-folha,.cap",l=[...r.querySelectorAll("h2,h3,h4")].filter(a=>y(a)&&a.compareDocumentPosition(e)&Node.DOCUMENT_POSITION_FOLLOWING&&(a.closest(n)||r).contains(e)&&a.closest(n)!==null),p=l[l.length-1];return p&&q(p).split(`
`)[0]||(o===1?f():"Tabela "+(t+1))}const k=/^(nf|n[\u00ba\u00b0o.]*\s*(da\s+)?(nota|nf)|nota( fiscal)?|n[u\u00fa]mero)\b/i,z=/^(?:NF\s*)?0*(\d{1,9})$/i;function I(e,t){const o={},r=[];let n=0,l=0;const p={};for(const i of t.rows){if(!y(i))continue;let s=0;for(const c of i.cells){if(!y(c)&&c.innerText.trim()==="")continue;for(;p[n+","+s];)s++;const d=c.colSpan||1,u=c.rowSpan||1,m=E(c);if(m){const g=e.utils.encode_cell({r:n,c:s});o[g]=m.t==="d"?{t:"d",v:m.v,z:m.z}:m,c.tagName==="TH"&&(o[g].s={font:{bold:!0}})}if(d>1||u>1){r.push({s:{r:n,c:s},e:{r:n+u-1,c:s+d-1}});for(let g=0;g<u;g++)for(let v=0;v<d;v++)(g||v)&&(p[n+g+","+(s+v)]=1)}s+=d,l=Math.max(l,s)}n++}for(let i=0;i<l;i++){const s=o[e.utils.encode_cell({r:0,c:i})];if(!(!s||s.t!=="s"||!k.test(String(s.v).trim())))for(let c=1;c<n;c++){const d=e.utils.encode_cell({r:c,c:i}),u=o[d],m=u&&u.t==="s"?z.exec(String(u.v).trim()):null;m&&(o[d]={t:"n",v:Number(m[1]),z:"0"})}}if(!n)return null;o["!ref"]=e.utils.encode_range({s:{r:0,c:0},e:{r:n-1,c:Math.max(0,l-1)}}),r.length&&(o["!merges"]=r);const a=[];for(const i in o){if(i[0]==="!")continue;const{c:s}=e.utils.decode_cell(i),c=o[i],d=String(c.t==="n"?c.v.toFixed(2):c.t==="d"?"00/00/0000":c.v).length;a[s]=Math.min(60,Math.max(a[s]||8,d+2))}return o["!cols"]=a.map(i=>({wch:i||10})),o}function S(e,t){let o=e.replace(/[\[\]:*?\/\\]/g," ").replace(/\s+/g," ").trim().slice(0,31)||"Tabela",r=2,n=o;for(;t.has(o.toLowerCase());){const l=" ("+r+++")";o=n.slice(0,31-l.length)+l}return t.add(o.toLowerCase()),o}function T(){const e=window.XLSX;if(!e){x("A biblioteca do Excel não carregou. Recarregue a página e tente de novo.");return}const t=document.getElementById("view")||document.querySelector(".content")||document.body,o=e.utils.book_new(),r=new Set;o.Props={Title:f(),Author:"Jarvis",Company:N(),CreatedDate:new Date};const n=[...t.querySelectorAll("table")].filter(a=>y(a)&&a.rows.length>1&&!a.closest('[aria-hidden="true"],.mgtip-pop')),l=n.map(a=>{const i=a.style.display;return a.style.display="none",[a,i]}),p=t.innerText.split(`
`).map(a=>a.replace(/ /g," ").trim()).filter(Boolean);if(l.forEach(([a,i])=>a.style.display=i),p.length){const a={},i=[];let s=null;for(const c of p){const d=b(c);d&&d.t!=="s"?s&&!s.v?s.v=d:i.push(s={a:"",v:d}):i.push(s={a:c,v:null})}a.A1={t:"s",v:f()+(h()?" · "+h():"")},i.forEach((c,d)=>{c.a&&(a[e.utils.encode_cell({r:d+1,c:0})]={t:"s",v:c.a}),c.v&&(a[e.utils.encode_cell({r:d+1,c:1})]=c.v)}),a["!ref"]=e.utils.encode_range({s:{r:0,c:0},e:{r:i.length,c:1}}),a["!cols"]=[{wch:70},{wch:18}],e.utils.book_append_sheet(o,a,S("Resumo",r))}if(n.forEach((a,i)=>{const s=I(e,a);s&&e.utils.book_append_sheet(o,s,S(L(a,i,n.length),r))}),!o.SheetNames.length){x("Nada para exportar nesta tela.");return}e.writeFile(o,B("xlsx"),{compression:!0}),x(`Excel gerado: ${o.SheetNames.length} aba(s).`)}function _(){const e=document.getElementById("view");if(!e)return window.print();document.querySelectorAll(".exp-cab").forEach(r=>r.remove());const t=document.createElement("div");t.className="exp-cab",t.innerHTML=`<b>Jarvis · ${C(f())}</b><span>${C([N(),h(),"emitido em "+new Date().toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"})].filter(Boolean).join(" · "))}</span>`,e.parentNode.insertBefore(t,e),document.body.classList.add("exp-imprimindo");const o=()=>{document.body.classList.remove("exp-imprimindo"),t.remove(),removeEventListener("afterprint",o)};addEventListener("afterprint",o),setTimeout(()=>window.print(),60)}const C=e=>String(e).replace(/[&<>"]/g,t=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[t]);function x(e){if(typeof toast=="function")toast(e);else{const t=document.getElementById("toast");t&&(t.textContent=e,t.classList.add("show"),setTimeout(()=>t.classList.remove("show"),2600))}}function M(){const e=document.querySelector(".pagehead .pageactions");!e||e.querySelector(".exp-btns")||e.insertAdjacentHTML("afterbegin",'<div class="exp-btns" role="group" aria-label="Exportar esta tela"><button class="small" data-exp="xlsx" title="Baixar as tabelas desta tela em Excel">Excel</button><button class="small" data-exp="pdf" title="Imprimir ou salvar esta tela em PDF">PDF</button></div>')}if(typeof shell=="function"){const e=shell;shell=function(){const t=e.apply(this,arguments);try{M()}catch{}return t}}window.Exportar={celula:b,celulaTd:E,excel:T,pdf:_},document.addEventListener("click",e=>{const t=e.target.closest("[data-exp]");if(t){e.preventDefault();try{t.dataset.exp==="pdf"?_():T()}catch(o){console.error(o),x("Não foi possível exportar: "+(o.message||o))}}});const F=`.exp-btns{display:flex;gap:6px}.exp-btns button{display:inline-flex;align-items:center;gap:6px}
.exp-cab{display:none}
@media print{
 @page{size:A4 landscape;margin:10mm}
 body:not(.pg-diag){background:#fff!important;color:#111!important}
 body:not(.pg-diag) .side,body:not(.pg-diag) main>header,body:not(.pg-diag) .pagehead,body:not(.pg-diag) .footer,body:not(.pg-diag) .fab,body:not(.pg-diag) #toast,body:not(.pg-diag) #erpdrop,body:not(.pg-diag) .mgtip-pop,body:not(.pg-diag) .rolatopo,body:not(.pg-diag) .guiabtn{display:none!important}
 body:not(.pg-diag) .erp{display:block!important}body:not(.pg-diag) main,body:not(.pg-diag) .content{margin:0!important;padding:0!important;max-width:none!important;width:auto!important;overflow:visible!important}
 body:not(.pg-diag) .tablewrap,body:not(.pg-diag) .tablebox{overflow:visible!important;max-height:none!important;box-shadow:none!important}
 body:not(.pg-diag) table{font-size:10px!important}body:not(.pg-diag) th,body:not(.pg-diag) td{padding:3px 6px!important}
 body:not(.pg-diag) tr,body:not(.pg-diag) .card,body:not(.pg-diag) .kpi{break-inside:avoid}
 /* A impressão geral do sistema esconde todo botão e todo .hero; na exportação, volta o conteúdo feito de botões
    (barras de gráfico, cartões clicáveis) e somem só os controles. */
 body.exp-imprimindo #view button,body.exp-imprimindo #view .hero{display:revert!important}
 body.exp-imprimindo #view :is(button.small,button.primary,button.quiet,.iconbtn,.guiabtn,.segtabs,.toolbar,.crmbar,.filters,.searchin,.rowacts,.fab,[data-exp]),
 body.exp-imprimindo #view input[type=checkbox],body.exp-imprimindo #view input[type=search]{display:none!important}
 body.exp-imprimindo .exp-cab{display:flex!important;justify-content:space-between;align-items:baseline;gap:16px;border-bottom:1px solid #ccc;padding:0 0 6px;margin:0 0 12px;font:12px Inter,"Segoe UI",sans-serif;color:#111}
 body.exp-imprimindo .exp-cab span{color:#555}}`,$=document.createElement("style");$.textContent=F,document.head.appendChild($)})();
