"use strict";(()=>{const i={log:null,estado:null,carregando:!1,erro:"",filtro:"",em:0},y=["Mercado Livre","Shopee","Magalu"],S={apto:["Apto (ensaio)","info"],emitida:["Emitida","info"],autorizada:["Autorizada","ok"],rejeitada:["Rejeitada","bad"],bloqueado:["Bloqueado","warn"]},M={enviada:["Enviada ao marketplace","ok"],nao_suportado:["Envio manual",""]},w=()=>new Date(Date.now()-3*36e5).toISOString().slice(0,10),v=()=>window.Cloud?.role==="owner",b=()=>db.gerencial?.fiscal?.fat_auto||{},$=()=>db.gerencial?.fiscal||{},p=()=>{page==="faturamento"&&render()};function l(t,e){const o={...$()};o.fat_auto={...o.fat_auto||{},...t},db.gerencial={...db.gerencial||{},fiscal:o},audit("Faturamento automático",e),save()}async function u(t){if(!(i.carregando||!window.Cloud?.ws||!t&&Date.now()-i.em<6e4)){i.carregando=!0,i.erro="";try{const[e,o]=await Promise.all([Cloud.client.from("fat_auto_log").select("*").eq("workspace_id",Cloud.ws).order("updated_at",{ascending:!1}).limit(2e3),Cloud.client.from("integrations").select("settings").eq("workspace_id",Cloud.ws).eq("provider","bling").maybeSingle()]);if(e.error)throw e.error;i.log=e.data||[],i.estado=o.data?.settings?.fat_auto||null,i.comNota=new Set(i.log.filter(s=>["autorizada","emitida"].includes(s.resultado)).map(s=>s.pedido))}catch(e){i.erro=e.message||String(e),i.log=i.log||[]}i.carregando=!1,i.em=Date.now(),p()}}const h=t=>t?new Date(t).toLocaleString("pt-BR",{day:"2-digit",month:"2-digit",hour:"2-digit",minute:"2-digit"}):"—";function C(){if(!window.Cloud?.ws)return'<div class="empty">Entre na conta para usar o faturamento automático.</div>';!i.log&&!i.carregando&&u(!0);const t=b(),e=$(),o=i.estado||{},s=o.ultima||{},d=i.log||[],n=v(),N=e.ambiente==="producao",m=t.modo==="producao"?"producao":"ensaio",q=o.pausado&&!(t.retomar_em&&t.retomar_em>o.pausado.em),_=w(),z=d.filter(a=>String(a.created_at||"").slice(0,10)>=_||String(a.updated_at||"").slice(0,10)>=_),c=a=>z.filter(r=>r.resultado===a).length,k={};for(const a of d.filter(r=>r.resultado==="bloqueado"))k[a.motivo]=(k[a.motivo]||0)+1;const j=Object.entries(k).sort((a,r)=>r[1]-a[1]).slice(0,6),F=d.filter(a=>!i.filtro||a.resultado===i.filtro).slice(0,300),f=(a,r,g="")=>`<li class="${a?"ok":"pend"}">${a?"✓":"•"} ${r}${g?` <span class="caption">${g}</span>`:""}</li>`;return`<div class="notice"><b>Faturamento automático.</b> De 15 em 15 minutos, 24 horas, o Jarvis emite a NF-e (Focus) dos pedidos pagos e com dados completos, confere se o pedido não foi cancelado e se o Bling ainda não emitiu, leva a nota para o DIFAL, envia ao Mercado Livre e à Shopee e, com "GNRE sozinha", gera e transmite a guia. Para quando 5 notas seguidas são rejeitadas e avisa por e-mail. Nunca cancela nota.</div>
 ${q?`<div class="notice fa-pausa"><b>Pausado em ${h(o.pausado.em)}:</b> ${esc(o.pausado.motivo)}. Confira as rejeições abaixo, corrija e retome.${n?' <button class="small primary" data-fa="retomar">Retomar</button>':""}</div>`:""}
 ${o.erro?`<div class="notice">Última rodada com erro: ${esc(o.erro)}</div>`:""}
 <div class="grid two" style="align-items:start">
  <section class="card"><div class="cardhead"><div><h2>Automação</h2><p class="caption">${t.ligado?`Ligada · modo ${m==="producao"?"<b>produção</b> (notas com valor fiscal)":"<b>ensaio</b> (só confere, não emite)"}`:"Desligada"}${o.em?` · última rodada ${h(o.em)}`:""}</p></div>
   ${n?`<button class="${t.ligado?"":"primary"}" data-fa="ligar">${t.ligado?"Desligar":"Ligar"}</button>`:""}</div>
   <div class="fa-cfg">
    <label>Modo<div class="segtabs"><button class="${m==="ensaio"?"active":""}" data-fa-modo="ensaio" ${n?"":"disabled"}>Ensaio</button><button class="${m==="producao"?"active":""}" data-fa-modo="producao" ${n?"":"disabled"}>Produção</button></div></label>
    <label>Canais<div class="row wrap">${y.map(a=>`<label class="check-l"><input type="checkbox" class="check" data-fa-canal="${esc(a)}" ${(t.canais?.length?t.canais:["Mercado Livre","Shopee"]).includes(a)?"checked":""} ${n?"":"disabled"}> ${a}</label>`).join("")}</div></label>
    <div class="row wrap"><label>Pedidos a partir de<input type="date" data-fa-campo="desde" value="${esc(t.desde||"")}" ${n?"":"disabled"}></label>
     <label>Máximo por dia<input type="number" min="1" data-fa-campo="limite_dia" value="${esc(t.limite_dia||400)}" style="width:100px" ${n?"":"disabled"}></label>
     <label>Por rodada<input type="number" min="1" max="60" data-fa-campo="por_rodada" value="${esc(t.por_rodada||30)}" style="width:90px" ${n?"":"disabled"}></label>
     <label>Valor máximo do pedido<input type="number" min="1" data-fa-campo="valor_max" value="${esc(t.valor_max||5e3)}" style="width:120px" ${n?"":"disabled"}></label></div>
    <label class="check-l"><input type="checkbox" class="check" data-fa-gnre ${t.gnre?"checked":""} ${n?"":"disabled"}> GNRE sozinha: gerar e transmitir as guias das notas novas nas UFs sem inscrição (o pagamento continua pelo arquivo do banco)</label>
   </div></section>
  <section class="card"><h2>Antes de ligar em produção</h2><ul class="fa-check">
   ${f(N,"NF-e do Jarvis em produção","Faturamento › Configuração da NF-e")}
   ${f(d.some(a=>a.modo==="ensaio"&&a.resultado==="apto"),"Ensaio rodado e conferido","pedidos aptos e bloqueios abaixo")}
   ${f(!!t.bling_parado,"Bling parado de emitir nota para esses canais",n?`<button class="small quiet" data-fa="bling">${t.bling_parado?"desmarcar":"marcar como feito"}</button>`:"")}
   ${f(!!(e.emitente?.endereco&&e.emitente?.ibge&&e.emitente?.cep),"Dados do emitente para a GNRE","DIFAL e GNRE › Configuração")}
  </ul><p class="caption">Sem o Bling parado, o mesmo pedido pode sair com duas notas. O Jarvis confere o pedido no Bling antes de cada emissão, mas o Bling não confere o Jarvis.</p></section>
 </div>
 <div class="grid kpis4" style="margin-top:16px">
  <div class="card kpi"><span class="kpil">${m==="producao"?"Emitidas hoje":"Aptos hoje (ensaio)"}</span><span class="kpiv">${m==="producao"?c("emitida")+c("autorizada")+c("rejeitada"):c("apto")}</span><span class="kpis">${s.emitidas!=null?`última rodada: ${s.emitidas||0} emitida(s), ${s.aptos||0} apto(s)`:""}</span></div>
  <div class="card kpi"><span class="kpil">Autorizadas hoje</span><span class="kpiv ok">${c("autorizada")}</span><span class="kpis">${d.filter(a=>a.resultado==="autorizada"&&a.marketplace==="enviada").length} enviada(s) ao marketplace</span></div>
  <div class="card kpi"><span class="kpil">Rejeitadas</span><span class="kpiv ${c("rejeitada")?"red":""}">${d.filter(a=>a.resultado==="rejeitada").length}</span><span class="kpis">${c("rejeitada")} hoje</span></div>
  <div class="card kpi"><span class="kpil">Bloqueados</span><span class="kpiv ${d.some(a=>a.resultado==="bloqueado")?"gold":""}">${d.filter(a=>a.resultado==="bloqueado").length}</span><span class="kpis">esperam correção</span></div>
 </div>
 ${j.length?`<section class="card" style="margin-top:16px"><h2>Por que pedidos ficaram de fora</h2><div class="tablewrap"><table><tbody>${j.map(([a,r])=>`<tr><td>${esc(a)}</td><td class="num">${r}</td></tr>`).join("")}</tbody></table></div></section>`:""}
 <div class="tablebox" style="margin-top:16px"><div class="tabletop"><div><h2>Pedidos avaliados</h2><p class="caption">${i.carregando?"Carregando…":`${d.length} registro(s)`}${i.erro?` · ${esc(i.erro)}`:""}</p></div>
  <div class="row"><div class="segtabs">${[["","Todos"],["autorizada","Autorizadas"],["emitida","Emitidas"],["rejeitada","Rejeitadas"],["bloqueado","Bloqueados"],["apto","Aptos"]].map(([a,r])=>`<button class="${i.filtro===a?"active":""}" data-fa-filtro="${a}">${r}</button>`).join("")}</div><button class="small" data-fa="atualizar">${icon("refresh")} Atualizar</button></div></div>
  <div class="tablewrap"><table><thead><tr><th>Pedido</th><th>Canal</th><th>Data</th><th class="num">Valor</th><th>Resultado</th><th>NF-e</th><th>Marketplace</th><th>Motivo</th><th>Atualizado</th></tr></thead><tbody>
  ${F.map(a=>{const[r,g]=S[a.resultado]||[a.resultado,""],[A,D]=M[a.marketplace]||[a.marketplace?String(a.marketplace).replace(/^erro: /,"Erro: "):"—",String(a.marketplace||"").startsWith("erro")?"bad":""];return`<tr><td class="mono">${esc(a.pedido)}</td><td>${esc(a.canal||"")}</td><td>${a.data_pedido?a.data_pedido.split("-").reverse().join("/"):""}</td><td class="num">${money(Number(a.valor)||0)}</td><td><span class="badge ${g}">${r}</span></td><td class="mono">${esc(a.numero||"")}</td><td>${a.resultado==="autorizada"?`<span class="badge ${D}" title="${esc(a.marketplace||"")}">${esc(A).slice(0,40)}</span>`:""}</td><td class="fa-motivo">${esc(a.motivo||"")}</td><td>${h(a.updated_at)}</td></tr>`}).join("")||'<tr><td colspan="9" class="empty">Nenhum pedido avaliado ainda. Ligue a automação (no modo ensaio primeiro).</td></tr>'}
  </tbody></table></div></div>`}document.addEventListener("click",t=>{const e=t.target.closest("[data-fa],[data-fa-modo],[data-fa-filtro]");if(!e)return;const o=e.dataset;if(o.faFiltro!==void 0){i.filtro=o.faFiltro,p();return}if(o.fa==="atualizar"){u(!0);return}if(!v())return toast("Só o dono muda o faturamento automático.");const s=b();if(o.faModo){if(o.faModo===s.modo||o.faModo==="ensaio"&&!s.modo)return;if(o.faModo==="producao"){if($().ambiente!=="producao")return toast("Passe a NF-e para produção antes (Faturamento › Configuração da NF-e).");if(!confirm("Modo PRODUÇÃO: o Jarvis vai emitir NF-e com valor fiscal sozinho, sem clique, para os pedidos pagos dos canais marcados. Confirma?"))return}l({modo:o.faModo},`modo ${o.faModo}`),toast(o.faModo==="producao"?"Modo produção: as notas saem na próxima rodada (até 15 min).":"Modo ensaio: nada é emitido."),p();return}if(o.fa==="ligar"){const d=!s.ligado;if(d&&s.modo==="producao"&&!confirm("Ligar a emissão automática em PRODUÇÃO (notas com valor fiscal)?"))return;l({ligado:d,desde:s.desde||w(),canais:s.canais?.length?s.canais:["Mercado Livre","Shopee"],modo:s.modo||"ensaio"},d?`ligado (${s.modo||"ensaio"})`:"desligado"),toast(d?"Ligado. A primeira rodada sai em até 15 minutos.":"Desligado."),p();return}if(o.fa==="retomar"){l({retomar_em:new Date().toISOString()},"retomado depois da pausa"),toast("Retomado: volta na próxima rodada."),setTimeout(()=>u(!0),1500);return}o.fa==="bling"&&(l({bling_parado:s.bling_parado?null:new Date().toISOString()},s.bling_parado?"Bling: emissão não confirmada como parada":"Bling parado de emitir (confirmado pelo dono)"),p())}),document.addEventListener("change",t=>{const e=t.target;if(!e.closest?.(".fa-cfg")||!v())return;const o=b();if(e.dataset.faCanal){const s=new Set(o.canais?.length?o.canais:["Mercado Livre","Shopee"]);e.checked?s.add(e.dataset.faCanal):s.delete(e.dataset.faCanal),l({canais:[...s]},`canais: ${[...s].join(", ")}`);return}if(e.hasAttribute("data-fa-gnre")){l({gnre:e.checked},`GNRE sozinha ${e.checked?"ligada":"desligada"}`);return}if(e.dataset.faCampo){const s=e.dataset.faCampo,d=s==="desde"?e.value||null:Math.max(1,Number(e.value)||0);l({[s]:d},`${s}: ${d}`)}}),window.FatAuto={view:C,carregar:u,temNota:t=>!!i.comNota?.has(t)}})();
