"use strict";(()=>{const v="brand/jarvis-192.png",b=()=>typeof db<"u"&&db&&db.gerencial||{},r=()=>b().empresa||{},m=()=>b().fiscal||{},n=e=>String(e??"").trim(),f=()=>n(r().nome_exibicao)||n(window.Cloud?.wsName)||"Minha empresa",t={nome:f,logo:()=>n(r().logo)||v,temLogo:()=>!!n(r().logo),assinatura:()=>n(r().assinatura)||"Equipe "+f(),escritorio:()=>n(r().escritorio)||"a contabilidade",segmento:()=>n(r().segmento),razao:()=>n(m().razao),cnpj:()=>String(m().cnpj||"").replace(/\D/g,""),uf:()=>n(m().uf).toUpperCase(),municipio:()=>n(m().municipio),regime:()=>n(m().regime),cnpjFmt:()=>{const e=t.cnpj();return e.length===14?e.replace(/^(\d{2})(\d{3})(\d{3})(\d{4})(\d{2})$/,"$1.$2.$3/$4-$5"):e},cidadeUF:()=>[t.municipio(),t.uf()].filter(Boolean).join("/"),nichoInfantil:()=>{const e=typeof normalized=="function"?normalized(t.segmento()):t.segmento().toLowerCase();return/brinquedo|infantil/.test(e)},assinar:e=>String(e??"").replace(/\{loja\}/g,t.assinatura()),podeEditar:()=>!window.Cloud?.ws||window.Cloud?.role==="owner"};window.Marca=t;const w=60*1024,i={logo:void 0,processando:!1},$=e=>Math.floor((e.length-e.indexOf(",")-1)*3/4);function E(e){return new Promise((a,s)=>{const o=new FileReader;o.onload=()=>a(o.result),o.onerror=()=>s(Error("Não consegui ler o arquivo.")),o.readAsDataURL(e)})}function y(e){return new Promise((a,s)=>{const o=new Image;o.onload=()=>a(o),o.onerror=()=>s(Error("Arquivo não é uma imagem válida.")),o.src=e})}async function x(e){if(!/^image\//.test(e.type||""))throw Error("Escolha um arquivo de imagem (PNG, JPG, WebP ou SVG).");const a=await y(await E(e));for(const s of[256,192,160,128,96]){const o=Math.min(1,s/Math.max(a.naturalWidth||a.width||s,a.naturalHeight||a.height||s)),d=Math.max(1,Math.round((a.naturalWidth||a.width||s)*o)),u=Math.max(1,Math.round((a.naturalHeight||a.height||s)*o)),l=document.createElement("canvas");l.width=d,l.height=u;const c=l.getContext("2d");c.clearRect(0,0,d,u),c.drawImage(a,0,0,d,u);for(const h of[.92,.8,.65,.5]){const g=l.toDataURL("image/webp",h);if(/^data:image\/webp/.test(g)&&$(g)<w)return g}const p=l.toDataURL("image/png");if($(p)<w)return p}throw Error("A imagem continua grande demais mesmo reduzida. Tente um logo mais simples.")}function S(){const e=r(),a=t.podeEditar(),s=a?"":"disabled",o=i.logo===void 0?n(e.logo):i.logo,d=(c,p,h,g)=>`<div class="field"><label for="de_${c}">${p}</label><input id="de_${c}" data-de="${c}" value="${esc(e[c]||"")}" placeholder="${esc(h)}" ${s} maxlength="120">${g?`<small class="caption">${g}</small>`:""}</div>`,u=m(),l=[u.razao,t.cnpjFmt(),t.cidadeUF(),u.regime].filter(Boolean).map(esc).join(" · ");return`${a?"":'<div class="notice">Só o administrador da empresa altera estes dados.</div>'}
 <section class="card"><div class="cardhead"><div><h2>Como a empresa aparece</h2><p class="caption">Nome e logo na barra lateral, no painel da TV e nos documentos; assinatura nas mensagens aos clientes.</p></div>${a?`<button class="small primary" data-de-salvar="1">${icon("check")} Salvar</button>`:""}</div>
  <div class="grid two">${d("nome_exibicao","Nome de exibição",window.Cloud?.wsName||"Ex.: Loja Exemplo","Aparece no menu, no painel e nos relatórios.")}
   ${d("assinatura","Assinatura das mensagens ao cliente","Equipe "+f(),"Vai no fim dos modelos de atendimento e das mensagens de CRM.")}
   ${d("escritorio","Escritório contábil","Ex.: Contabilidade Silva","Citado nas telas de fechamento, obrigações e emissão de notas.")}
   ${d("segmento","Segmento","Ex.: brinquedos, moda, casa e decoração",'Liga recursos próprios do ramo (ex.: brinquedos → "Próximo brinquedo" no CRM).')}</div>
  <div class="field" style="margin-top:14px"><label>Logo</label><div class="row wrap" style="gap:14px;align-items:center">
   <img src="${esc(o||v)}" alt="Logo atual" style="width:72px;height:72px;object-fit:contain;border-radius:12px;background:var(--panel2);border:1px solid var(--line);padding:6px">
   ${a?`<label class="small upbtn" style="cursor:pointer"><input type="file" accept="image/*" data-de-logo="1" hidden> ${i.processando?"Reduzindo…":"Escolher imagem"}</label>${o?'<button class="small quiet" data-de-semlogo="1">Remover logo</button>':""}`:""}
   <small class="caption">PNG, JPG, WebP ou SVG. O Jarvis reduz para até 256 px e menos de 60 KB.${o?"":" Sem logo, aparece o símbolo do Jarvis."}</small></div></div>
 </section>
 <section class="card"><div class="cardhead"><div><h2>Dados fiscais</h2><p class="caption">Razão social, CNPJ, cidade/UF e regime ficam em Regras fiscais (usados na nota, nas propostas, no CNAB e nas obrigações).</p></div><button class="small" data-nav="parametros">Abrir Regras fiscais</button></div>
  <p>${l||'<span class="gold">Preencha os dados da empresa em Regras fiscais.</span>'}</p></section>`}function q(){if(!t.podeEditar()){toast("Só o administrador altera os dados da empresa.");return}const e={...r()};document.querySelectorAll("[data-de]").forEach(a=>{e[a.dataset.de]=a.value.trim()}),i.logo!==void 0&&(e.logo=i.logo||""),db.gerencial={...db.gerencial||{},empresa:e},i.logo=void 0,save();try{audit("Dados da empresa","nome, logo e assinatura atualizados")}catch{}toast("Dados da empresa salvos."),render()}document.addEventListener("click",e=>{const a=e.target.closest("[data-de-salvar],[data-de-semlogo]");if(a){if(a.dataset.deSalvar){q();return}a.dataset.deSemlogo&&(i.logo="",render())}}),document.addEventListener("change",async e=>{const a=e.target.closest("[data-de-logo]");if(!a||!a.files?.[0]||!t.podeEditar())return;const s={};document.querySelectorAll("[data-de]").forEach(o=>s[o.dataset.de]=o.value),i.processando=!0,render();try{i.logo=await x(a.files[0]),toast("Logo pronto. Clique em Salvar.")}catch(o){toast(o.message||String(o))}finally{i.processando=!1}render(),document.querySelectorAll("[data-de]").forEach(o=>{s[o.dataset.de]!=null&&(o.value=s[o.dataset.de])})}),t.tela={id:"dadosempresa",icone:"folder",titulo:"Dados da empresa",view:S,sub:"Nome, logo, assinatura das mensagens, escritório contábil e segmento da empresa.",reduzirLogo:x}})();
