"use strict";(()=>{Object.assign(paths,{raiox:"M4 19h16 M6 16V9 M10 16V5 M14 16v-4 M18 16V8"});const p={base:""};window.Reiniciar?.registrar(p,["base"]);const h=s=>{const[n,e]=s.split("-").map(Number);return new Date(n,e-2,1,12).toLocaleDateString("sv-SE").slice(0,7)},m=s=>{const[n,e]=s.split("-").map(Number);return new Date(n,e-1,1,12).toLocaleDateString("pt-BR",{month:"short",year:"numeric"}).replace(".","")},o=s=>s==null?"—":(s*100).toFixed(1).replace(".",",")+"%",c=s=>s==null?"—":`${s>0?"+":s<0?"−":""}${Math.abs(s*100).toFixed(2).replace(".",",")} p.p.`,d=s=>s>5e-5?"green":s<-5e-5?"red":"";function g(s,n){const e=n?Math.min(100,Math.abs(s)/n*100):0;return`<span class="rxbar ${s<0?"neg":"pos"}"><i style="width:${e.toFixed(1)}%"></i></span>`}const b=(s,n)=>new Date(Date.parse(s+"T12:00:00Z")+n*864e5).toISOString().slice(0,10);function f(){const s=new Date().toLocaleDateString("sv-SE"),n={recIni:b(s,-7),recFim:b(s,-1),baseIni:b(s,-35),baseFim:b(s,-8)},e=new Map;for(const r of db.orders||[]){const t=Number(r.gross)||0;if(t<=0||!r.date)continue;const l=r.date>=n.recIni&&r.date<=n.recFim?"r":r.date>=n.baseIni&&r.date<=n.baseFim?"b":null;if(!l)continue;const i=e.get(r.platform)||{b:{v:0,t:0,n:0},r:{v:0,t:0,n:0}};e.set(r.platform,i),i[l].v+=t,i[l].t+=Number(r.fee)||0,i[l].n++}return[...e].filter(([,r])=>r.r.n>=5&&r.b.v>0&&r.r.v>0).map(([r,t])=>{const l=t.b.t/t.b.v,i=t.r.t/t.r.v,u=i-l;return{k:r,base:l,rec:i,delta:u,n:t.r.n,venda:t.r.v,impacto:-u*t.r.v*30/7,reajuste:i<1?(1-l)/(1-i)-1:0,alerta:Math.abs(u)>=.015&&t.r.v>=1e3&&t.r.n>=20}}).sort((r,t)=>t.venda-r.venda)}function v(){const s=f();if(!s.length)return"";const n=s.filter(e=>e.alerta);return`<section class="tablebox"><div class="tabletop"><div><h2>Tarifa por canal: última semana</h2><p class="caption">7 dias fechados contra os 28 anteriores. Mudou 1,5 ponto ou mais, o Jarvis avisa (Alertas e relatórios › Tarifa de um canal mudou).</p></div>${n.length?`<span class="badge ${n.some(e=>e.delta>0)?"bad":"ok"}">${n.length} canal(is) com mudança</span>`:'<span class="badge ok">estável</span>'}</div><div class="tablewrap"><table><thead><tr><th>Canal</th><th class="num">28 dias antes</th><th class="num">Última semana</th><th class="num">Mudança</th><th class="num">Impacto no mês</th><th class="num">Reajuste p/ manter o líquido</th></tr></thead><tbody>
  ${s.map(e=>`<tr><td><strong>${esc(e.k)}</strong><br><span class="caption">${e.n} pedidos na semana</span></td><td class="num">${o(e.base)}</td><td class="num">${o(e.rec)}</td><td class="num ${e.alerta?d(-e.delta):""}"><strong>${c(e.delta)}</strong></td><td class="num ${e.alerta?d(e.impacto):""}">${e.alerta?(e.impacto<0?"−":"+")+money(Math.abs(e.impacto)):"—"}</td><td class="num">${e.alerta&&e.delta>0?"+"+o(e.reajuste):"—"}</td></tr>`).join("")}</tbody></table></div>
  <p class="caption" style="padding:0 14px 12px">Reajuste aproximado: trata a tarifa como percentual da venda (a parte fixa por pedido pesa mais nos itens baratos). Pedidos muito recentes podem ainda não ter a tarifa final do marketplace.</p></section>`}function M(){if(!window.Margem?.raiox)return'<div class="empty">Carregando…</div>';const s=typeof month=="string"?month:new Date().toLocaleDateString("sv-SE").slice(0,7),n=[...new Set((db.orders||[]).map(a=>String(a.date||"").slice(0,7)))].filter(a=>a&&a<s).sort().reverse(),e=p.base&&n.includes(p.base)?p.base:n.includes(h(s))?h(s):n[0];if(!e)return v()+'<div class="empty">Precisa de pelo menos dois meses de vendas para comparar.</div>';const r=v(),t=Margem.raiox(e,s),l=Math.max(.001,...t.fatores.map(a=>Math.abs(a.efeito)),Math.abs(t.canais.mix),Math.abs(t.canais.marg)),i=[...n.slice(0,5).reverse(),s],u=Margem.tendencia(i),y=t.produtos.itens.filter(a=>a.contrib<-5e-5).slice(0,15),$=[...t.produtos.itens].reverse().filter(a=>a.contrib>5e-5).slice(0,5);return`<div class="crmbar"><span>Comparando <strong>${esc(m(s))}</strong> (competência do cabeçalho) com</span><select data-rx="base" aria-label="Mês de comparação">${n.slice(0,18).map(a=>`<option value="${a}" ${a===e?"selected":""}>${esc(m(a))}</option>`).join("")}</select>
  <span class="caption">Margem de contribuição = vendas − tarifa − frete pago pela loja − custo dos produtos − tributos (pedidos com custo cadastrado).</span></div>
 <div class="grid kpis4"><div class="card kpi"><span class="kpil">Margem ${esc(m(e))}</span><span class="kpiv">${o(t.margemA)}</span><span class="kpis">${money(t.a.lucro)} em ${money(t.a.venda)}</span></div>
  <div class="card kpi"><span class="kpil">Margem ${esc(m(s))}</span><span class="kpiv ${d(t.variacao)}">${o(t.margemB)}</span><span class="kpis">${money(t.b.lucro)} em ${money(t.b.venda)}</span></div>
  <div class="card kpi"><span class="kpil">Variação</span><span class="kpiv ${d(t.variacao)}">${c(t.variacao)}</span><span class="kpis">${t.variacao!=null?`${money(t.b.venda*(t.variacao||0))} a ${t.variacao<0?"menos":"mais"} no mês, no volume atual`:""}</span></div>
  <div class="card kpi"><span class="kpil">Fora da conta</span><span class="kpiv">${t.semCusto.b}</span><span class="kpis">pedido(s) sem custo cadastrado em ${esc(m(s))}</span></div></div>
 ${r}
 <div class="grid two" style="align-items:start">
 <section class="tablebox"><div class="tabletop"><h2>De onde veio a variação</h2><span class="caption">em pontos percentuais da margem</span></div><div class="tablewrap"><table><thead><tr><th>Fator</th><th class="num">${esc(m(e))}</th><th class="num">${esc(m(s))}</th><th class="num">Efeito na margem</th><th style="min-width:120px"></th></tr></thead><tbody>
  ${t.fatores.map(a=>`<tr><td>${a.t}</td><td class="num">${o(a.a)}</td><td class="num">${o(a.b)}</td><td class="num ${d(a.efeito)}"><strong>${c(a.efeito)}</strong></td><td>${g(a.efeito,l)}</td></tr>`).join("")}
  <tr><td><strong>Total</strong></td><td class="num">${o(t.margemA)}</td><td class="num">${o(t.margemB)}</td><td class="num ${d(t.variacao)}"><strong>${c(t.variacao)}</strong></td><td></td></tr></tbody></table></div>
  <p class="caption" style="padding:0 14px 12px">Cada linha mostra o peso do fator nas vendas. Tarifa subindo de 20% para 22% tira 2 pontos da margem.</p></section>
 <section class="tablebox"><div class="tabletop"><h2>Por canal</h2><span class="caption">mix: vender mais no canal de margem menor · margem: o canal ficou pior</span></div><div class="tablewrap"><table><thead><tr><th>Canal</th><th class="num">Peso nas vendas</th><th class="num">Margem</th><th class="num">Efeito</th></tr></thead><tbody>
  ${t.canais.itens.map(a=>`<tr><td><strong>${esc(a.k)}</strong></td><td class="num">${o(a.wA)} → ${o(a.wB)}</td><td class="num">${o(a.ma)} → <span class="${d((a.mb??0)-(a.ma??0))}">${o(a.mb)}</span></td><td class="num ${d(a.contrib)}">${c(a.contrib)}</td></tr>`).join("")}
  <tr><td colspan="3">Efeito mix (troca de peso entre canais)</td><td class="num ${d(t.canais.mix)}">${c(t.canais.mix)}</td></tr><tr><td colspan="3">Efeito margem (cada canal em si)</td><td class="num ${d(t.canais.marg)}">${c(t.canais.marg)}</td></tr></tbody></table></div></section></div>
 <section class="tablebox"><div class="tabletop"><div><h2>Produtos que mais puxaram a margem para baixo</h2><p class="caption">Contribuição de cada produto para a variação (a soma de todos os produtos dá a variação total) e o que mudou nele, por unidade.</p></div><div class="row" style="gap:6px;flex-wrap:wrap"><button class="small" data-nav="margem">${icon("radar")} Preço mínimo (Radar)</button><button class="small" data-nav="concorrencia">${icon("tag")} Ajustar preços no Mercado Livre</button><button class="small" data-nav="catalogo">${icon("tag")} Preço por canal (Shopee, Magalu)</button></div></div><div class="tablewrap"><table><thead><tr><th>Produto</th><th class="num">Vendas ${esc(m(s))}</th><th class="num">Margem</th><th class="num">Mix</th><th class="num">Margem do item</th><th class="num">Contribuição</th><th>O que mudou · o que fazer</th></tr></thead><tbody>
  ${y.map(a=>`<tr><td><strong>${esc(a.b?.nome||a.a?.nome||a.k)}</strong><br><span class="caption mono">${esc(a.k)}</span></td><td class="num">${money(a.b?.venda||0)}<br><span class="caption">${Math.round(a.b?.u||0)} un.</span></td><td class="num">${o(a.ma)} → <span class="${(a.mb??0)<0?"red":""}">${o(a.mb)}</span></td><td class="num ${d(a.eMix)}">${c(a.eMix)}</td><td class="num ${d(a.eMarg)}">${c(a.eMarg)}</td><td class="num red"><strong>${c(a.contrib)}</strong></td><td class="caption">${esc(a.diag)}</td></tr>`).join("")||'<tr><td colspan="7" class="empty">Nenhum produto piorou a margem. ✓</td></tr>'}</tbody></table></div></section>
 ${$.length?`<section class="tablebox"><div class="tabletop"><h2>Os que mais ajudaram</h2></div><div class="tablewrap"><table><thead><tr><th>Produto</th><th class="num">Vendas</th><th class="num">Margem</th><th class="num">Contribuição</th><th>O que mudou</th></tr></thead><tbody>${$.map(a=>`<tr><td><strong>${esc(a.b?.nome||a.a?.nome||a.k)}</strong></td><td class="num">${money(a.b?.venda||0)}</td><td class="num">${o(a.ma)} → ${o(a.mb)}</td><td class="num green">${c(a.contrib)}</td><td class="caption">${esc(a.diag)}</td></tr>`).join("")}</tbody></table></div></section>`:""}
 <section class="tablebox"><div class="tabletop"><h2>Últimos meses</h2><span class="caption">peso de cada fator nas vendas</span></div><div class="tablewrap"><table><thead><tr><th>Mês</th><th class="num">Vendas (com custo)</th><th class="num">Tarifa</th><th class="num">Frete</th><th class="num">Custo</th><th class="num">Tributos</th><th class="num">Margem</th></tr></thead><tbody>
  ${u.map(a=>`<tr><td>${esc(m(a.mes))}</td><td class="num">${money(a.venda)}</td><td class="num">${o(a.tarifa)}</td><td class="num">${o(a.frete)}</td><td class="num">${o(a.custo)}</td><td class="num">${o(a.tributos)}</td><td class="num"><strong>${o(a.margem)}</strong></td></tr>`).join("")}</tbody></table></div></section>`}document.addEventListener("change",s=>{const n=s.target.closest('[data-rx="base"]');n&&(p.base=n.value,render())}),addPage("raiox","raiox","Raio-X da margem",M,"Por que a margem mudou de um mês para o outro: tarifa, frete, custo, tributos, canais e produtos — e o que fazer.","",()=>{})})();
